---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ikurtz-cbci-aws-reinvent-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap # (EFS Access Point) - static at this time
  fileSystemId: fs-0cbc163a1b125530e
  directoryPerms: "700"

