apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudbees-ci
  name: cjoc-master-management
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]  # Define verbs for Pods resource
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]  # Define verbs for Pod/exec resource
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]  # Define verbs for Pods/log resource
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "watch", "patch", "update"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]   # Define verbs for Services resource
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "get", "update", "delete", "list", "watch"]

