apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cloudbees-ci
  name: managed-master-hibernation-monitor
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
