OperationsCenter:
  JavaOpts: >-
    -Dcom.cloudbees.masterprovisioning.kubernetes.KubernetesMasterProvisioning.displayReplication=true
    -Dcom.cloudbees.masterprovisioning.kubernetes.KubernetesMasterProvisioning.deleteClaim=true
  HostName: ikurtz.aws.sa-demo.beescloud.com
  Protocol: https
  Platform: eks
  Ingress:
    Class: alb
    Annotations:
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      alb.ingress.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      #alb.ingress.kubernetes.io/aws-load-balancer-type: "nlb"
      alb.ingress.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:268150017804:certificate/e59ff147-8f49-4154-acab-7fa83e6d0aeb"
      alb.ingress.kubernetes.io/aws-load-balancer-connection-idle-timeout: "70"
  Resources:
    Limits:
      # OperationsCenter.Resources.Limits.Cpu -- CPU limit to run Operations Center
      # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu
      Cpu: 2
      # OperationsCenter.Resources.Limits.Memory -- Memory limit to run Operations Center
      # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
      Memory: 8G
    Requests:
      # OperationsCenter.Resources.Requests.Cpu -- CPU request to run Operations Center
      # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-cpu
      Cpu: 1
      # OperationsCenter.Resources.Requests.Memory -- Memory request to run Operations Center
      # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#meaning-of-memory
      Memory: 4G
  
Persistence:
  StorageClass: ikurtz-cbci-aws-reinvent-efs-sc

## Install Default RBAC roles and bindings
rbac:
  # rbac.install -- Install `role`/`rolebindings`/`serviceAccount`.
  # If false (and rbac is enabled in the cluster anyway), provide valid names for all service accounts.
  install: true
  
  # rbac.serviceAccountName -- Name of the service account Operations Center will run as
  serviceAccountName: cjoc
  # rbac.masterServiceAccountName -- Name of the service account Jenkins masters will run as
  masterServiceAccountName: jenkins
  # rbac.agentServiceAccountName -- Name of the service account Jenkins agents will run as
  agentsServiceAccountName: jenkins-agents
  # rbac.hibernationMonitorServiceAccountName -- Name of the service account the Hibernation monitor will run as (if enabled)
  hibernationMonitorServiceAccountName: managed-master-hibernation-monitor
