OperationsCenter:
  JavaOpts: >-
    -Dcom.cloudbees.masterprovisioning.kubernetes.KubernetesMasterProvisioning.displayReplication=true
  HostName: <your-domain>.aws.<username>.ps.beescloud.com
  Protocol: https
  Platform: eks
  Ingress:
    Class: alb
    Annotations:
      alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      alb.ingress.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      #alb.ingress.kubernetes.io/aws-load-balancer-type: "nlb"
      alb.ingress.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:<account-id>:certificate/<cert-id>"
      alb.ingress.kubernetes.io/aws-load-balancer-connection-idle-timeout: "70"
  
Persistence:
  StorageClass: ikurtz-cbci-aws-reinvent-efs-sc
